[project]
name = "fastapi-url-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.4",
    "fastapi[standard]>=0.116.1",
    "redis[hiredis]>=6.2.0",
    "uvicorn[standard]>=0.35.0",
]
