[project]
name = "fastapi-url-shortener"
version = "0.1.0"
description = "fastapi URL shortener"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "docker-compose",
    "fastapi[standard]>=0.115.14",
    "requests>=2.32.4",
]
